### ISSUE TITLE
parallax problem

### ISSUE THREAD

**Issue by MedoElkamaly** [florent37/MaterialViewPager#17] opened 2015-05-10 09:05 UTC
parallax is not working right when using a lower dpi device (mdpi) 
![g](https://cloud.githubusercontent.com/assets/5602736/7553632/9ab59b20-f70c-11e4-8a8a-592f6c29f511.gif)

**Comment by bluebirdzx** [comment] 2015-05-10 12:03
1280*720 is  same problem,but  sample-debug.apk  is ok

**Comment by florent37** [comment] 2015-05-10 19:35
can you check on the version **1.0.3.1** please

**Comment by bluebirdzx** [comment] 2015-05-11 05:36
hi，1.0.3.1  is same problem
![screenshot_2015-05-11-13-33-15](https://cloud.githubusercontent.com/assets/1531848/7559073/c13e03dc-f7e2-11e4-91e6-9f12c4c75248.png)

**Comment by florent37** [comment] 2015-05-11 07:00
Dont know where this happens... Any idea ?

**Comment by GHEEV** [comment] 2015-05-13 20:17
I saw the issue yesterday, testing a new version of my app with new version of your library. The version 1.0.0 didn't happened this issue... something you changed in the code...

**Comment by MedoElkamaly** [comment] 2015-05-14 06:14
Did you tested it on mdpi device?

**Comment by GHEEV** [comment] 2015-05-14 06:20
Oh sorry, no... It's a xdpi device.

Em qui, 14 de mai de 2015 03:14, MedoElkamaly <notifications@github.com>
escreveu:

**Comment by GHEEV** [comment] 2015-05-17 03:30
I was changing somethings on my application, when I tried to implement "navigation bar color" and "navigation translucent" in styles-v21 and after that, the cards overlapped the tabs strips.. I'm thinking about that, and MAYBE, the problem is about the smartphones which there is fullscreen, like the both examples here and my application now (because the navigation bar is transparent, using all screen to show the content), make sense no?

**Comment by MedoElkamaly** [comment] 2015-05-19 06:44
I didn't change any thing on the app, all I have done is run the same app on different device.
On the xhdpi device the parallax work perfectly (still there is some issue with the title), and on the mdpi device the cards overlapped the tabs strips (like the example)

**Comment by bluebirdzx** [comment] 2015-05-23 07:24
sample_debug.apk 1.04 is ok  but my ower builder 1.04 is bad, maybe  is  other library cause

**Comment by bluebirdzx** [comment] 2015-05-23 07:26
can you give  me  other  libs source code? thanks of lot

**Comment by florent37** [comment] 2015-05-23 08:30
I used https://github.com/ksoichiro/Android-ObservableScrollView for the scroll listening.
I don't understand why your own 1.0.4 would be different with sample_debug.apk 1.04. Can you try with emulators & send me a configuration which always fails please ?

(and thanks for your reports :+1:, helps me improving this lib )

**Comment by Tibolte** [comment] 2015-06-08 13:32
Could this be resolved with the Design Support Library? CollapsingToolbarLayout looks like an alternative to ObservableScrollView. Support from 2.1 :)

**Comment by florent37** [comment] 2015-06-10 12:12
can you try with the "1.0.4.3" please ?

**Comment by florent37** [comment] 2015-06-10 12:13
@Tibolte it's not the same purpose, CollapsingToolbarLayout isn't an alternative, it works with CoordinatorLayout, I tried to implement it for recreate materialviewpager, but no succeed...

**Comment by florent37** [comment] 2015-06-10 15:25
try with the 1.0.5

**Closed by florent37** 2015-06-10 15:25 UTC
Labels: bug, help wanted
