### ISSUE TITLE
AppCompat does not support current theme features

### ISSUE THREAD

**Issue by pmk2429** [florent37/MaterialViewPager#125] opened 2015-08-01 22:36 UTC
I am trying to solve this problem but it doesnt seem to work for me.
I have styles.xml and v21/styles.xml.

My styles.xml looks like this:  

    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar"/>

        <style name="AppTheme.NoActionBar">
            <item name="colorPrimary">@color/colorPrimary</item>
            <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
            <item name="android:windowTranslucentStatus">true</item>  

    
My v21/styles.xml looks like this  
  

    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>

        <item name="android:windowContentTransitions">true</item>
        <item name="android:windowAllowEnterTransitionOverlap">true</item>
        <item name="android:windowAllowReturnTransitionOverlap">true</item>
        <item name="android:windowSharedElementEnterTransition">@android:transition/move</item>
        <item name="android:windowSharedElementExitTransition">@android:transition/move</item>
        <item name="android:windowTranslucentStatus">true</item>

        </style>
Now I have created a BaseActivity in order to extend the Material NavDrawer in all the activities. In order to do so, it is required for me to first call the

     setContentView(R.layout.activity_main);
        super.onCreate(savedInstanceState);
If I change this order then the activities which will extend the BaseACtivity wont be able to identify the controls in the BaseActivity and it gives me error for not able to find controls.

So it seems I am in deadlock.

Please let me know what to do.

Thanks in Advance.

**Comment by vj-1023** [comment] 2015-08-08 16:29
@florent37 I m facing the same problem, till i don't use the style theme everything looks dim dull white, after copying the styles file i get the same error as above.

Anyway to resolve this ?


@pmk2429  Did you find a solution ?

**Comment by Ashok-Varma** [comment] 2015-08-09 09:25
@pmk2429 @vj-1023 
Don't just copy those styles and replace with your styles. Keep your old styles as it is.

Check my styles 

styles.xml
    <style name="AppTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/PrimaryColor</item>
        <item name="colorPrimaryDark">@color/DarkPrimaryColor</item>
        <item name="colorAccent">@color/AccentColorOrange</item>
        <item name="colorControlHighlight">@color/LightPrimaryColor</item>
        <item name="android:textColorPrimary">@color/PrimaryText</item>
        <item name="android:textColorSecondary">@color/SecondaryText</item>
        <item name="windowActionModeOverlay">true</item>
        <item name="actionModeBackground">@drawable/background_action_mode</item>
    </style>

    <style name="AppTheme.MaterialViewPager" parent="AppTheme.Base">
        

        <item name="android:textColorPrimary">@android:color/white</item>
        <item name="drawerArrowStyle">@style/DrawerArrowStyle</item>
        <item name="android:windowTranslucentStatus" tools:targetApi="21">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

        
        <item name="colorControlNormal">@android:color/white</item>
        <item name="actionBarTheme">@style/AppTheme.ActionBarTheme</item>

        
        <item name="android:navigationBarColor" tools:targetApi="21">@color/navigationBarColor</item>
        <item name="android:windowDrawsSystemBarBackgrounds" tools:targetApi="21">true</item>
    </style>

styles-v21.xml
no need anything the new android tools picks everything from here.

and now in manifest.xml

<application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:windowSoftInputMode="stateHidden" >
        <activity
            android:name=".Home"
            android:label="@string/title_activity_home" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".MovieDetailsNewsStandActivity"
            android:label="@string/title_activity_movie_details_news_stand"
            android:theme="@style/AppTheme.MaterialViewPager"
            android:parentActivityName=".Home" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="com.ashokvarma.yifytorrentsyts.Home" />
        </activity>
    </application>

**Comment by vj-1023** [comment] 2015-08-09 09:28
Yeh i did that and its working now the issue is m using the scrollFragment
but the headerView and pagerTabStrips dont scroll up along with the
fragment.

Any clue why is this happening.
I have used the same code as your main activity.

**Comment by Ashok-Varma** [comment] 2015-08-09 09:33
Once check the sample fragments. Here are the links
https://github.com/florent37/MaterialViewPager/blob/master/sample/src/main/res/layout/fragment_scroll.xml
https://github.com/florent37/MaterialViewPager/blob/master/sample/src/main/java/com/github/florent37/materialviewpager/sample/fragment/ScrollFragment.java

Use need to register a framgment as show in the code

**Comment by Ashok-Varma** [comment] 2015-08-09 09:36
@vj-1023 
Once check the sample fragments. Here are the links
https://github.com/florent37/MaterialViewPager/blob/master/sample/src/main/res/layout/fragment_scroll.xml
https://github.com/florent37/MaterialViewPager/blob/master/sample/src/main/java/com/github/florent37/materialviewpager/sample/fragment/ScrollFragment.java

Use need to register a framgment as show in the code @vj-1023

**Comment by vj-1023** [comment] 2015-08-09 09:54
Cool , let me try and get back to you.
Thank you very much

**Comment by Ashok-Varma** [comment] 2015-08-09 09:58
@vj-1023 
1) First in fragment you need to you com.github.ksoichiro.android.observablescrollview.ObservableScrollView instead of scrollview and all other views has there own variants of observablescrollview.
2) you need to register your fragment to material viewpager based on which observablescrollview you use.

Just go through examples and check.

**Comment by Ashok-Varma** [comment] 2015-08-10 05:11
@florent37  I think you can close this issue now.

**Comment by pmk2429** [comment] 2015-08-10 07:00
@Ashok-Varma 

Tried everything. Still cant get it to work.
Getting the same error. 

It seems that the order of setting the   


    setContentView(R.layout.activity_main);
    super.onCreate(savedInstanceState);


  
has to be reversed.But if I do, then I won't be able to extend the Material NavDrawer in all activities.

Any suggestions?

**Comment by Ashok-Varma** [comment] 2015-08-10 07:09
@pmk2429  did you use two styles with different name in styles.xml.

If you are using latest support libraries and Plugins you don' t need v21/styles.xml. for basic theme attributes like primary color ...etc .

you can delete it.

And specify the problem clearly, i was still not able to understand problem that clearly

**Comment by pmk2429** [comment] 2015-08-10 07:56
Kudos... I get it to work!
Had to move some initialization from onCreate() to onPostCreate().
Everything works fine now.

Thanks for the help.

Appreciate it.

**Comment by Ashok-Varma** [comment] 2015-08-10 08:26
@pmk2429 @vj-1023 
So all your problems solved ??
Can we close this issue ?

**Comment by vj-1023** [comment] 2015-08-10 10:31
Hi i tried what u said also saw the examples from the sample project

I m getting this issue https://youtu.be/prA6izwV0uA

The header is not scrolling up along the svroll fragment.
What is causing this ?
How do i solve this ?

**Comment by Ashok-Varma** [comment] 2015-08-10 12:39
I think it's because you have not registered your scrollview to that.
add this to your fragment

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mScrollView = (ObservableScrollView) view.findViewById(R.id.scrollView);

        MaterialViewPagerHelper.registerScrollView(getActivity(), mScrollView, null);
    }


are you using observablescrollview instead of scrollview ??
if so give the obersvable scrollview this id "scrollView"

**Comment by vj-1023** [comment] 2015-08-10 12:44
Sorted.
Lets close.
Thank you.

Also for readers guys the creators of this library and the library itself
are very helpful.

Thanks guys.

**Comment by florent37** [comment] 2015-08-10 12:48
Thanks @Ashok-Varma for your help :+1:

**Closed by florent37** 2015-08-10 12:48 UTC

**Comment by Ashok-Varma** [comment] 2015-08-10 13:35
Always Welcome @florent37
